### PR TITLE
Use executeJSONRPC() instead of executebuiltin()

### PR DESCRIPTION
**Pull request by dagwieers**
This makes use of `xbmc.executeJSONRPC()` rather than use `xbmc.executebuiltin()`.

The use of `xbmc.executebuiltin()` is being discouraged (and may become deprecated), and using `xbmc.executeJSONRPC()` has the advantage of not requiring to flatten the payload into a formatted string. It accepts data-structures.

### CODE REVIEW

**Comment by dagwieers** [comment]
I tested this just now using the Netflix add-on, and it seems to time-out.
It is unclear to me why, because we are doing exactly this in some of our add-ons.

**Review by ruuk — COMMENTED** [review]
Looks good, I just need to test it and then I'll merge it.

**Comment by dagwieers** [comment]
We use this jsonrpc function in 3 different add-ons now: plugin.video.vrt.nu, service.upnext, screensaver.turnoff. And soon script.module.inputstreamhelper as well.

In the meantime I have improved this jsonrpc() function to support batch-mode (so running more than one JSONRPC action in a single call), but you don't need this.

**Review by ruuk — APPROVED** [review]
Looks good!

**Pull request merged**
