### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by romanvm**
This PR fixes incompatibility with Python 3.

### CODE REVIEW

**Comment by ruuk** [comment]
Thanks for the PR.

There's another PR (#1) that fixes this differently. I'm wondering if there is some extra advantage to the method you've used here over the other that one because otherwise I'm leaning towards that as it is a simpler change.

**Comment by romanvm** [comment]
For starters, base64 is more efficient in terms of resulting data size. Currently this is de facto standard encoding for converting binary data to ASCII text and back.

But I have doubts that you need to use this bytes <> text conversion at all.

**Comment by CastagnaIT** [comment]
please wait to merge, today or next day i want to do some tests
is true base64 creates a shorter string than hexify,

but i'm not convinced of the ascii decode

**Comment by romanvm** [comment]
> but i'm not convinced of the ascii decode

In Python 3 your string literal is a Unicode string. You'll get `TypeError` when you try to format a `bytes` object produced by b64encode into a `str`. You need to decode your bytes to a str, and since base64 is ASCII-only, no need to use full UTF-8 decoder.

**Comment by CastagnaIT** [comment]
I thank you for the explanation had not taken into consideration the .format, now i have reconnected my neurons😂

**Comment by CastagnaIT** [comment]
i made a try (libreELEC with py3 with NF https://github.com/CastagnaIT/plugin.video.netflix/pull/211) but this stuck to a UnicodeDecodeError
https://paste.kodi.tv/dasubufevu.kodi

**Comment by romanvm** [comment]
I stand myself corrected: .format() is type-safe and won't raise TypeError but for non-text data, including bytes, repr() function is used to convert them to text, which is not what you expect here.

Regarding the error, I need to know what data are send by a sender, and what raw data are received by the receiver to understand what is happening.

**Comment by CastagnaIT** [comment]
the log attached try to make a call to addonsignals.makecall:
`
    result = AddonSignals.makeCall(
        source_id=g.ADDON_ID,
        signal=callname,
        data=data,
        timeout_ms=16000)
`

with this data:

callname= 'update_profiles_data'
data= None

**Comment by romanvm** [comment]
I still need to see what **raw** data the receiver got. Maybe you can add additional logging or use a debugger.

**Comment by CastagnaIT** [comment]
i have put some debug log point to addonsignals
this can help?
https://paste.kodi.tv/zubasugeka.kodi

**Comment by romanvm** [comment]
Stupid error. I'll update the PR soon.

**Comment by romanvm** [comment]
I have updated the code.

**Comment by CastagnaIT** [comment]
i'll let you know tomorrow

**Comment by CastagnaIT** [comment]
Tested in both py2 - py3 working as expected

**Comment by ruuk** [comment]
Thanks @romanvm for the PR and @CastagnaIT for the testing. I'll update the Kodi repo soon.

**Pull request merged**
