### PR TITLE
Fix TypeError: JSON object must be str, not 'bytes'

### LINKED ISSUE #7: AddonSignals fails on Python 3.5
There is a known issues on Python 3 with Python 3.5 and older causing `json.loads()` to fail on **bytes** or **bytestring**.

This issue came up when performing unit tests on AddonSignals.
See: https://travis-ci.org/dagwieers/service.upnext/builds/616895177

```
$ coverage run -p -m unittest discover
...E
======================================================================
ERROR: test_to_addon_signals (test.test_encoding.TestEncoding)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dagwieers/service.upnext/test/test_encoding.py", line 71, in test_to_addon_signals
    decoded_data = AddonSignals._decodeData('["%s"]' % encoded_data)  # pylint: disable=protected-access
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/AddonSignals.py", line 21, in _decodeData
    return json.loads(base64.b64decode(data[0]))
  File "/opt/python/3.5.6/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
----------------------------------------------------------------------
Ran 4 tests in 0.004s
FAILED (errors=1)
```

### PR DESCRIPTION
**Pull request by dagwieers**
This fixes an issue with  json.loads()  on Python 3.5.

This fixes #7

### CODE REVIEW

**Comment by dagwieers** [comment]
Could this be merged? Cause our own integration tests are failing on Python 3.5 because of this.
https://travis-ci.org/dagwieers/service.upnext/builds/616895177

**Comment by CastagnaIT** [comment]
from the source code i've always seen that kodi uses version 3.7 not 3.5

**Comment by dagwieers** [comment]
@CastagnaIT Well, I preferred not to have to support Python 3.5 myself either, but Debian Stretch is still shipping Python 3.5 and Kodi specifically supports Python 3.5 and newer. So we have to follow suit: https://github.com/im85288/service.upnext/pull/90#issuecomment-557795853

If Kodi decides to drop Python 3.5 support we can reconsider, but before then we have to support it.

**Comment by CastagnaIT** [comment]
oh my that sh@@, okay, i'm going to go to throwing the pc out the window...LOL

**Comment by CastagnaIT** [comment]
so i suggest a different approch:
```
if sys.version_info <= (3,5,9) and isinstance(json_data, bytes):
   json_data = json_data.decode('utf-8')
```

**Comment by dagwieers** [comment]
What is needed to get this moving forward?

*I also opened 3 other PRs that have not seen any activity*

**Comment by ruuk** [comment]
> What is needed to get this moving forward?
> 
> _I also opened 3 other PRs that have not seen any activity_

I did assign all your PRs to myself for review when you added them, I just haven't had time to look at them yet.

If you'd like, you're welcome to take ownership of this add-on. Just let me know when you PR an update to the Kodi repo and I'll comment about the change of ownership in the PR.

**Comment by dagwieers** [comment]
I do not necessarily want to take ownership, but if it becomes unmaintained I might as well add the integration/unit tests, CI, code coverage, etc. The code is pretty easy to maintain.

For UpNext we will need to add the infrastructure for testing notifications as well, so I might as well reuse it for Addon Signals as well.

**Review by ruuk — COMMENTED** [review]
Looks good. I just need to test and then I'll merge.

**Review by ruuk — APPROVED** [review]
Looks great!

**Comment by ruuk** [comment]
PR'd to the Kodi repo: https://github.com/xbmc/repo-scripts/pull/1242

**Pull request merged**
